trigger:
  branches:
    include:
      - main

variables:
  Major: 1
  Minor: 0

name: $(Major).$(Minor)$(Rev:.r)

stages:
  - stage: Build
    pool:
      name: 'Default'

    variables:
      buildConfiguration: 'Release'
      name: PackageVersion
      value: '$(build.buildNumber)'

    jobs: 
      - job: Build
        steps:
        - task: UseNode@1
          displayName: Use NPM
          inputs: 
            version: 20.x

        - script: npm install -g allure-commandline
          displayName: Install Allure

        - task: DotNetCoreCLI@2
          displayName: Restore solution Test.Api.Framework.sln
          inputs:
            command: restore
            projects: '**/Test.Api.Framework.sln'

        - task: SonarQubePrepare@7
          displayName: SonarQube Prepare
          inputs:
            SonarQube: 'SonarQube'
            scannerMode: 'dotnet'
            projectKey: 'Integration_Layer_Test.Api.Framework_fab068c0-c529-47f6-b263-22fbfa14140e'
            extraProperties: |
              sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/Test.Api.Framework.Tests/TestResults/**/coverage.opencover.xml
              sonar.scanner.skipJreProvisioning=true

        - task: DotNetCoreCLI@2
          displayName: 'Build solution Test.Api.Framework.sln 🧱'
          inputs:
            command: build
            projects: '**/Test.Api.Framework.sln'
            arguments: '--configuration $(BuildConfiguration)'

        - script: dotnet test --logger trx --collect:"XPlat Code Coverage;ExcludeByAttribute=GeneratedCodeAttribute;Format=opencover,cobertura"
          displayName: 'Run Unit Tests 🧪'
          condition: succeededOrFailed()

        - task: PublishTestResults@2
          displayName: 'Publish Test Results 📊'
          condition: succeededOrFailed()
          inputs:
            testRunner: VSTest
            testResultsFiles: '**/*.trx'

        - task: PublishCodeCoverageResults@2
          condition: always()
          displayName: 'Publish Code Coverage Results 📊'
          inputs:
            summaryFileLocation: '**/coverage.cobertura.xml'

        - task: SonarQubeAnalyze@7
          displayName: SonarQube Analyse 🧐

        - task: SonarQubePublish@7
          displayName: SonarQube Publish
          inputs:
            pollingTimeoutSec: '300'

        - task: PublishAllureReport@1
          displayName: Publish Allure Report 📊
          inputs:
            allureVersion: '2.32.0'
            testResultsDir: '$(Build.SourcesDirectory)/Test.Api.Framework.Tests/bin/Debug/net8.0/allure-results'
            reportName: 'Unit Test Report'

        - task: DotNetCoreCLI@2
          displayName: 'Package Test.Api.Framework.sln 📦'
          inputs:
            command: pack
            versioningScheme: byBuildNumber
            arguments: --output $(Build.ArtifactStagingDirectory)
          condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

        - task: CopyFiles@2
          displayName: 'Copy All Files to Directory'
          condition: always()
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: |
              **/*
              !.git/**/*  
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifacts to Location'
          inputs:
            PathtoPublish: '$(build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

        - task: DotNetCoreCLI@2
          displayName: 'Push Nuget To Feed 🚀'
          inputs:
            command: 'push'
            packagesToPush: '$(Agent.BuildDirectory)/**/Test.Api.Framework*.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: 'bb11a7ed-6d1d-4e29-8e36-7d57ea1c9e98/1fee8d63-45f4-4b02-b3e9-333b57a39147'
          condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))